[package]
name = "just-a-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = "0.7"
tokio = { version = "1.2", features = ["macros", "time", "fs", "rt-multi-thread"] }
futures = "0.3"